name: GameU
version: '${project.version}'
main: dev.gameu.Gameu
api-version: '1.20'

commands:
  trophy:
    usage: /trophy
    description: Allows a player to view all earned trophys
  addTrophy:
    usage: /addTrophy <player>
    description: Adds the players held item to the recipient's trophy inventory.
  event:
    usage: /event [create <name> | delete]
    description: "Teleports a player to an event"

permissions:
  GameU.admin:
    description: "Admin permission set"
    default: op

